Poc/formik
ZupIT/horusec pull request #431
Opened 2021-04-16 14:02 UTC by lucasgarciazup

**- What I did**

**- How to verify it**

**- Description for the changelog**

2021-04-26 18:35 UTC, lucasbrunozup requested changes

2021-04-26 18:35 UTC, lucasbrunozup commented on horusec-manager/src/components/Calendar/index.tsx
> +        error={touched && !!error && !!value}
Tem como alterar a cor dos erros ? Usar a cor do tema, colors.input.error para que possa atender acessibilidade.

![image](https://user-images.githubusercontent.com/69604366/116131669-0e9d4500-a6a3-11eb-97fd-4ab33268440c.png)

2021-04-26 18:35 UTC, lucasbrunozup commented on horusec-manager/src/components/Calendar/index.tsx
> +        error={touched && !!error && !!value}
E a tradução, deu certo ?

2021-04-26 18:35 UTC, lucasbrunozup commented on horusec-manager/src/pages/Internal/Vulnerabilities/index.tsx
> +                  style={{
![image](https://user-images.githubusercontent.com/69604366/116132348-d3e7dc80-a6a3-11eb-83a9-4ee8a05e7b85.png)

Conseguimos deixar o item de Severidade, um pouco mais proximo do layout original ?

2021-04-26 18:35 UTC, lucasbrunozup commented on horusec-manager/src/pages/Internal/Vulnerabilities/index.tsx
> +  console.log(filters.vulnSeverity);
Remover console.log

2021-04-26 18:35 UTC, lucasbrunozup commented on horusec-manager/src/pages/External/Auth/Horusec/CreateAccount/Password/index.tsx
> +          console.log(props);
Reemover console.log

2021-04-26 18:35 UTC, lucasbrunozup commented on horusec-manager/src/pages/External/Auth/Horusec/CreateAccount/Password/index.tsx
> +  const ValidationScheme = Yup.object({
Ficou dahora essa validação, vai ajudar na acessibilidade também! Valeu! 👍🏼

2021-04-28 13:58 UTC, lucasgarciazup commented on horusec-manager/src/pages/External/Auth/Horusec/CreateAccount/Password/index.tsx
> +          console.log(props);
removido1

2021-04-28 13:58 UTC, lucasgarciazup commented on horusec-manager/src/pages/Internal/Vulnerabilities/index.tsx
> +  console.log(filters.vulnSeverity);
removido

2021-04-28 13:59 UTC, lucasgarciazup commented on horusec-manager/src/components/Calendar/index.tsx
> +        error={touched && !!error && !!value}
cor resolvida

2021-04-29 11:01 UTC, merged