service: improve tests and service funtions
ZupIT/horusec pull request #727
Opened 2021-10-27 17:47 UTC by iancardosozup

This commits add a ton of tests on service implementation, refactor on some adding more incisive assertions.

Signed-off-by: Ian Cardoso <ian.cardoso@zup.com.br>

**- What I did**

**- How to verify it**

**- Description for the changelog**

2021-10-29 19:37 UTC, iancardosozup commented on internal/services/formatters/service_test.go
> +		assert.Equal(t, "omething", result)
actually not, i tought it was but it's a bug, the function should return `something` but returns `omething` instead, i will fix it.

2021-11-03 12:32 UTC, matheusalcantarazup requested changes

2021-11-03 12:32 UTC, matheusalcantarazup commented on internal/services/formatters/service.go
> +	return path.Join(projectSubPath, filepathWithFileName)
Change to `filepath.Join` instead. The [path](https://pkg.go.dev/path) package does not deal with Windows paths.

2021-11-03 12:32 UTC, matheusalcantarazup commented on internal/services/formatters/service.go
> +func (s *Service) removeHorusecFolder(pathFromFile string) string {
Same ideia from comment above about the arg name.

2021-11-03 12:32 UTC, matheusalcantarazup commented on internal/services/formatters/service_test.go
> +		cfg.ProjectPath = testutil.GoExample1
Fill the fields directly as above.

2021-11-03 12:32 UTC, matheusalcantarazup commented on internal/services/formatters/service_test.go
> +		cfg := &config.Config{}
Same here.

2021-11-03 14:00 UTC, matheusalcantarazup approved these changes

2021-11-03 14:31 UTC, merged