chore(tests): move Mock implementations to testutil pkg
ZupIT/horusec pull request #753
Opened 2021-11-08 13:59 UTC by matheusalcantarazup

Previously each mock implementation of structs that is used by tests was
implemented on your own package, which add some unnecessary testing
dependencies on main packages.

This commit move all mocks implementation to testutil package and change
their references.

Note that the `internal/utils/mock` package was also removed and their
code was moved to testutil package to centralize all testing stuffs
only on testutil package.

Signed-off-by: Matheus Alcantara <matheus.alcantara@zup.com.br>

**- What I did**

**- How to verify it**

**- Description for the changelog**

2021-11-10 13:23 UTC, wiliansilvazup requested changes
to not get too confused, what do you think of having a file split of "mock", "e2e tests" "unit tests" and others? or doesn't it make sense?

2021-11-10 13:43 UTC, matheusalcantarazup commented
> to not get too confused, what do you think of having a file split of "mock", "e2e tests" "unit tests" and others? or doesn't it make sense?

Are you saying for example use `testutil/requirements_mock.go` instead? I think that would be good.

About unit tests and e2e I don't think soo. Some funcs and const can be used in both tests.

2021-11-11 14:28 UTC, iancardosozup approved these changes

2021-11-18 17:21 UTC, matheusalcantarazup commented on internal/utils/testutil/request_mock.go
> +type RequestMock struct {
This is good!
We should remove this `RequestMock` implementation and change their reference or make an alias `type RequestMock request.Mock`? What do you think?

2021-11-19 11:29 UTC, nathanmartinszup commented on internal/utils/testutil/request_mock.go
> +type RequestMock struct {
Any of the solutions sound good to me, maybe the alias to keep all in the same place.

2021-11-22 11:25 UTC, nathanmartinszup approved these changes

2021-11-22 13:37 UTC, wiliansilvazup commented
> > to not get too confused, what do you think of having a file split of "mock", "e2e tests" "unit tests" and others? or doesn't it make sense?
> 
> Are you saying for example use `testutil/requirements_mock.go` instead? I think that would be good.
> 
> About unit tests and e2e I don't think soo. Some funcs and const can be used in both tests.

oh great :)

2021-11-22 13:37 UTC, wiliansilvazup approved these changes

2021-11-22 13:37 UTC, wiliansilvazup commented
sync your branch with main and you can merge this pr :)

2021-11-22 17:00 UTC, merged