e2e:chore - tests for enable owasp dependency check flag
ZupIT/horusec pull request #804
Opened 2021-11-22 14:48 UTC by oliveirafelipezup

**- What I did**
Create test for enable owasp dependecy check flag
**- How to verify it**

**- Description for the changelog**

2021-11-22 17:45 UTC, matheusalcantarazup requested changes

2021-11-22 17:45 UTC, matheusalcantarazup commented on e2e/commands/start/start_test.go
> +	})
This test seems already been implemented on #793. Please remove from this pr

2021-11-23 12:05 UTC, lucasbrunozup requested changes

2021-11-23 12:05 UTC, lucasbrunozup commented on e2e/commands/start/start_test.go
> +			Expect(session.Out.Contents()).To(ContainSubstring(fmt.Sprintf(`\"enable_owasp_dependency_check\": %s,\n`, testutil.NormalizePathToAssertInJSON(oaspDependencyCheck))))
The `testutil.NormalizePathToAssertInJSON` function is unnecessary!

2021-11-23 18:35 UTC, nathanmartinszup commented on e2e/commands/start/start_test.go
> +		oaspDependencyCheck := "true"
Typo in `oaspDependencyCheck` -> `owaspDependencyCheck`

2021-11-23 18:35 UTC, nathanmartinszup commented on e2e/commands/start/start_test.go
> +				testutil.StartFlagEnableOwaspDependencyCheck: oaspDependencyCheck,
Here too `oaspDependencyCheck` -> `owaspDependencyCheck`

2021-11-24 17:27 UTC, wiliansilvazup approved these changes

2021-11-25 11:44 UTC, matheusalcantarazup approved these changes

2021-11-29 18:35 UTC, lucasbrunozup requested changes

2021-11-29 18:35 UTC, lucasbrunozup commented on e2e/commands/start/start_test.go
> -	When("--information-severity is passed", func() {
Why was this test deleted?

2021-12-01 13:26 UTC, wiliansilvazup commented on e2e/commands/start/start_test.go
> -	When("--information-severity is passed", func() {
@oliveirafelipezup

2021-12-02 12:16 UTC, matheusalcantarazup requested changes

2021-12-02 12:16 UTC, matheusalcantarazup commented on e2e/commands/start/start_test.go
> +			Expect(session.Out.Contents()).To(ContainSubstring(fmt.Sprintf(`\"enable_owasp_dependency_check\": %s,\n`, owaspDependencyCheck)))
Can we add a new Expected that check that the log message "Running OwaspDependencyCheck" is printed? With this we can sure that dependency check is started.

2021-12-02 12:16 UTC, matheusalcantarazup commented on e2e/commands/start/start_test.go
> +			Expect(session.Out.Contents()).To(ContainSubstring(fmt.Sprintf(`\"enable_owasp_dependency_check\": %s,\n`, owaspDependencyCheck)))
Can we add a new Expected that check that the log message "Running OwaspDependencyCheck" is printed? With this we can sure that dependency check is started.

2021-12-07 12:22 UTC, matheusalcantarazup commented on e2e/commands/start/start_test.go
> +			Expect(session.Out.Contents()).To(ContainSubstring(fmt.Sprintf(`\"enable_owasp_dependency_check\": %s,\n`, owaspDependencyCheck)))
The assert added is confusing. If the test is about checking that dependency check is running why `Expect(session.Out.Contents()).To(ContainSubstring("{HORUSEC_CLI} The tool was ignored for run in this analysis: OwaspDependencyCheck"))` was added instead `Expect(session.Out.Contents()).To(ContainSubstring("Running OwaspDependencyCheck"))`?

2021-12-07 12:39 UTC, lucasbrunozup approved these changes

2021-12-27 11:08 UTC, wiliansilvazup commented
I'm going to close this PR for now, because as it's saying in [this code](https://github.com/ZupIT/horusec/blob/79234a0ea90a055349fde1dbc423084340c24a9a/internal/services/formatters/generic/dependency_check/formatter.go#L44), the owasp dependency check tool will only run if enable Docker in the analysis. So this implementation is not valid for e2e tests :)

2021-12-27 11:08 UTC, closed without merging