lint:chore - updating lint config file
ZupIT/horusec pull request #811
Opened 2021-11-24 12:57 UTC by nathanmartinszup

Signed-off-by: Nathan Martins <nathan.martins@zup.com.br>

**- What I did**
Adding [gofumpt](https://github.com/mvdan/gofumpt), [gci](https://github.com/daixiang0/gci) linters and fixing import prefixes path. Some commented linters were also added, the idea is that they are uncommented one by one and the related errors are corrected, for each one will be separate pull requests opened with the corrections.

Depends on #809 which contains all the import and gofumpt  fixes.

**- How to verify it**

**- Description for the changelog**

2021-11-24 13:03 UTC, wiliansilvazup requested changes

2021-11-24 13:03 UTC, wiliansilvazup commented on .golangci.yml
> +    equire-explanation: false # don't require an explanation for nolint directives @TODO enable why no lint
```suggestion
    require-explanation: false # don't require an explanation for nolint directives @TODO enable why no lint
```

Should not be `require` ?

2021-11-24 13:23 UTC, nathanmartinszup commented on .golangci.yml
> +    equire-explanation: false # don't require an explanation for nolint directives @TODO enable why no lint
Done

2021-11-25 11:58 UTC, matheusalcantarazup approved these changes

2021-11-29 17:08 UTC, wiliansilvazup approved these changes

2021-11-29 17:08 UTC, merged