engine:chore - add test for HS-JAVASCRIPT-19 rule.
ZupIT/horusec pull request #812
Opened 2021-11-24 14:10 UTC by lucasbrunozup

Unit test for `HS-JAVASCRIPT-19` rule.

Signed-off-by: lucas.bruno <lucas.bruno@zup.com.br>

2021-11-24 17:10 UTC, wiliansilvazup requested changes
Update examples folder with main branch

2021-11-24 17:30 UTC, lucasbrunozup commented
> Update examples folder with main branch

Done

2021-11-24 18:12 UTC, lucasbrunozup commented on internal/services/engines/javascript/rules.go
> +			regexp.MustCompile(`Access-Control-Allow-Origin["|'|:][\s|,][\s|"|']['|"|\*]['|"|\*]\D`),
I changed the rule to get another very common scenario in javascript.

`res.header("Access-Control-Allow-Origin", "*");`

![image](https://user-images.githubusercontent.com/69604366/143292533-bfa994a4-741b-40f2-b844-3e4b4c0ad53f.png)

2021-11-24 18:36 UTC, wiliansilvazup approved these changes

2021-11-24 19:42 UTC, iancardosozup approved these changes

2021-11-25 11:54 UTC, matheusalcantarazup approved these changes

2021-11-25 19:39 UTC, nathanmartinszup approved these changes

2021-11-25 19:40 UTC, merged