logs:chore - improve logs when analysis gets errors
ZupIT/horusec pull request #855
Opened 2021-12-07 14:26 UTC by iancardosozup

Signed-off-by: Ian Cardoso <ian.cardoso@zup.com.br>

**- What I did**

**- How to verify it**

**- Description for the changelog**

2021-12-07 14:52 UTC, matheusalcantarazup requested changes

2021-12-07 14:52 UTC, matheusalcantarazup commented on internal/enums/errors/errors.go
> +	" Found no rails project syntax")
I think that would be better "Brakeman only works on Ruby On Rails project."

2021-12-07 14:52 UTC, matheusalcantarazup commented on internal/enums/errors/errors.go
> +	" Found no rails project syntax")
Also I think that `{HORUSEC_CLI}` is not necessary, since the log already have `HORUSEC_CLI` prefix, this would be redundant.

2021-12-07 19:13 UTC, matheusalcantarazup requested changes

2021-12-07 19:13 UTC, matheusalcantarazup commented on internal/enums/errors/errors.go
> +var ErrNotFoundRailsProject = errors.New("brakeman only function on Ruby On Rails project")
I think that the "works" should be used instead "function".

2021-12-07 20:39 UTC, matheusalcantarazup approved these changes

2021-12-08 16:09 UTC, nathanmartinszup approved these changes

2021-12-08 16:31 UTC, merged