kubernetes:chore - Improvements Tests of all Kubernetes Rules
ZupIT/horusec pull request #961
Opened 2022-01-31 11:41 UTC by wiliansilvazup

Add improvements for swift rules with scenarios vulnerables and safe codes in yours tests.
Follow the issue #630 for more details.

Signed-off-by: wilian <wilian.silva@zup.com.br>

2022-02-07 17:51 UTC, nathanmartinszup approved these changes

2022-02-08 12:19 UTC, iancardosozup approved these changes

2022-02-08 12:20 UTC, iancardosozup requested changes
make your commit verified with GPG key @wiliansilvazup

2022-02-08 12:56 UTC, matheusalcantarazup approved these changes

2022-02-09 15:53 UTC, merged