[docker]:[feature] - Validate Docker version from the Docker API
ZupIT/horusec pull request #965
Opened 2022-01-31 19:18 UTC by luiguip

Signed-off-by: Luis Guilherme de A <luisguilhermepdea@gmail.com>

**- What I did**

I changed the way the version of docker is retrieved, from a shell command execution to Docker API.

**- How to verify it**

With the docker running, run the horusec and it will validate the Docker version, from the Docker API.

**- Description for the changelog**
The log error message of an error with the docker validation had changed. Now few steps of preprocessing are necessary to retrieve the version.

2022-01-31 19:52 UTC, matheusalcantarazup requested changes
The `Validate` function could be simplified to this:
```func Validate() error {
	version, err := validateIfDockerIsInstalled()
	if err != nil {
		return err
	}
	return validateIfDockerIsRunningInMinVersion(version)
}
```
And `validateIfDockerIsSupported` could be removed.

2022-01-31 19:52 UTC, matheusalcantarazup commented on internal/controllers/requirements/docker/docker.go
> +			messages.MsgErrorWhenCheckRequirementsDocker, errors.New(err.Error()),
Just use `err` instead of `errors.New(err.Error())`

2022-01-31 19:52 UTC, matheusalcantarazup commented on internal/controllers/requirements/docker/docker.go
>  func execDockerVersion() (string, error) {
This function should be renamed to something like `getDockerVersion() (string, error)`

2022-01-31 19:52 UTC, matheusalcantarazup commented on internal/controllers/requirements/docker/docker.go
> +	return getVersionAndSubVersion(response)
We can remove `extractDockerVersionFromString` function and use directly `getVersionAndSubVersion`

2022-01-31 21:10 UTC, luiguip commented
Requested changes done.

2022-02-01 11:47 UTC, nathanmartinszup approved these changes

2022-02-01 12:30 UTC, matheusalcantarazup approved these changes
LGTM

Thanks very much for your contribution @luiguip

2022-02-01 12:32 UTC, merged