docs: add issues section
ZupIT/horusec pull request #991
Opened 2022-02-15 22:18 UTC by HenriqueZup

Signed-off-by: Henrique Rodrigues <henrique.rodrigues@zup.com.br>

**- What I did**
I added the issues section
**- How to verify it**
Access the CONTRIBUTING.md file of this branch, check section 2.3
**- Description for the changelog**
Adding an issue section as a prerequisite before contributing with a PR

2022-02-16 11:19 UTC, iancardosozup requested changes

2022-02-16 11:19 UTC, iancardosozup commented on CONTRIBUTING.md
> +- **[Burg report](https://github.com/ZupIT/horusec/issues/new?assignees=&labels=bug&template=bug_report.md):** Create a report to help us improve
typo

2022-02-16 11:34 UTC, iancardosozup commented on CONTRIBUTING.md
> +- **[Burg report](https://github.com/ZupIT/horusec/issues/new?assignees=&labels=bug&template=bug_report.md):** Create a report to help us improve
there is also a typo in `Burg report`

2022-02-16 13:39 UTC, nathanmartinszup approved these changes

2022-02-16 14:17 UTC, matheusalcantarazup requested changes
Btw, do we really need this scope and project? Isn't that the function of tags?

cc @nathanmartinszup @wiliansilvazup @iancardosozup

2022-02-16 14:17 UTC, matheusalcantarazup commented on CONTRIBUTING.md
> +**[Project][Scope]: Title Description**
I think we can change to "Project:Scope - Tittle description" so we can follow the same pattern [here](https://github.com/ZupIT/horusec/blob/bbbb2d1f40ed0145b865c04e359179de5219e0a7/CONTRIBUTING.md#pkgtype---description)

2022-02-16 14:17 UTC, matheusalcantarazup commented on CONTRIBUTING.md
> +**Example: [Horusec-cli][Improvement]: Suggestion for CLI installation experience**
So this example would be changed to `Horusec-cli:Improvement: Suggestion for CLI installation experience`

2022-02-16 18:47 UTC, iancardosozup approved these changes

2022-02-18 21:35 UTC, wiliansilvazup commented
> Btw, do we really need this scope and project? Isn't that the function of tags?
> 
> cc @nathanmartinszup @wiliansilvazup @iancardosozup

Yeah, this was arranged with the technical writer team!

2022-02-21 10:45 UTC, matheusalcantarazup approved these changes

2022-02-22 15:59 UTC, merged